In [1]:
import numpy as np
import pandas as pd



In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv('covid_toy.csv')

In [4]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [5]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [6]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [7]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.drop(columns=['has_covid']), df['has_covid'], test_size=0.2)

In [9]:
x_train

age  gender  fever   cough       city
96   51  Female  101.0  Strong    Kolkata
95   12  Female  104.0    Mild  Bangalore
87   47    Male  101.0  Strong  Bangalore
68   54  Female  104.0  Strong    Kolkata
20   12    Male   98.0  Strong  Bangalore
..  ...     ...    ...     ...        ...
71   75  Female  104.0  Strong      Delhi
1    27    Male  100.0    Mild      Delhi
57   49  Female   99.0  Strong  Bangalore
21   73    Male   98.0    Mild  Bangalore
75    5    Male  102.0    Mild    Kolkata

[80 rows x 5 columns]

# 1. Aam Zindagi

In [10]:
si = SimpleImputer()
x_train_fever = si.fit_transform(x_train[['fever']])

x_test_fever = si.fit_transform(x_test[['fever']])
x_train_fever

array([[101.        ],
       [104.        ],
       [101.        ],
       [104.        ],
       [ 98.        ],
       [100.78571429],
       [100.        ],
       [ 98.        ],
       [ 99.        ],
       [100.        ],
       [104.        ],
       [ 99.        ],
       [ 98.        ],
       [103.        ],
       [100.        ],
       [101.        ],
       [101.        ],
       [100.        ],
       [ 98.        ],
       [104.        ],
       [100.78571429],
       [100.        ],
       [103.        ],
       [101.        ],
       [100.78571429],
       [104.        ],
       [100.78571429],
       [ 98.        ],
       [ 98.        ],
       [ 98.        ],
       [102.        ],
       [100.78571429],
       [101.        ],
       [104.        ],
       [104.        ],
       [101.        ],
       [ 99.        ],
       [100.        ],
       [ 99.        ],
       [102.        ],
       [ 98.        ],
       [103.        ],
       [100.78571429],
       [100

In [11]:
x_train_fever.shape

(80, 1)

In [14]:
#ordinal ecoding

oe = OrdinalEncoder(categories=[['Mild', 'Strong']])
x_train_cough = oe.fit_transform(x_train[['cough']])

x_test_cough = oe.fit_transform(x_test[['cough']])

x_train_cough.shape

(80, 1)

In [ ]:
#onhot  ecoding

ohe = OneHotEncoder(drop='first', sparse_output=False)
x_train_gender_city = ohe.fit_transform(x_train[['gender','city']])

x_test_gender_city = ohe.fit_transform(x_test[['gender','city']])

x_train_gender_city.shape

(80, 4)

In [18]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [20]:
#extracting age
x_train_age = x_train.drop(columns=['gender', 'fever', 'cough', 'city'])

x_test_age = x_test.drop(columns=['gender', 'fever', 'cough', 'city'])
x_train_age.shape

(80, 1)

In [22]:
x_train_transformed = np.concatenate([x_train_age, x_train_fever, x_train_cough,x_train_gender_city], axis=1)

x_test_transformed = np.concatenate([x_test_age, x_test_fever, x_test_cough, x_test_gender_city], axis=1)

x_train_transformed

array([[ 51.        , 101.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 12.        , 104.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 47.        , 101.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 54.        , 104.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 12.        ,  98.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 20.        , 100.78571429,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 19.        , 100.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 40.        ,  98.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 14.        ,  99.        ,   0.        ,   0.        ,
          0.    

In [24]:
x_train_transformed.shape

(80, 7)

2. Mentos Zindagi

In [25]:
from sklearn.compose import ColumnTransformer

In [26]:
transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(), ['fever']),
    ('tnf2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),
    ('tnf3', OneHotEncoder(drop='first', sparse_output=False),['gender', 'city'])
], remainder='passthrough')

In [30]:
transformer.fit_transform(x_train)

array([[101.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  51.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  12.        ],
       [101.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  47.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  54.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  12.        ],
       [100.78571429,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  20.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  19.        ],
       [ 98.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  40.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          0.    

In [31]:
transformer.fit_transform(x_train).shape

(80, 7)