In [2]:
# import numpy module
import numpy as np


In [3]:
# create 1 dimensional array
arr1=np.ones(5)
print(arr1)

[1. 1. 1. 1. 1.]


In [4]:
a1=np.zeros(5)
a1

array([0., 0., 0., 0., 0.])

In [5]:
type(a1)

numpy.ndarray

In [6]:
ar1=np.ones(3,dtype=int)
ar1

array([1, 1, 1])

In [7]:
# create two dimensional array containing 3 elements in each row. defacto type of an item in numpy is float
arr2=np.ones((2,3),dtype=float)
arr2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
# verify the type of variable
type(arr2)

numpy.ndarray

In [9]:
# create a numpy array having 4 blocks, 2 rows and 3 columns

arr3=np.ones((4,2,3),dtype=int)
arr3

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [10]:
a1.dtype

dtype('float64')

In [11]:
# using dtype keyword
arr3.dtype

dtype('int64')

In [12]:
# ndim and shape keywords
print("Dimension of array",arr1.ndim)
print("Dimension of array",arr3.ndim)
print("Shape of an array",arr3.shape)
print("Shape of array",arr2.shape)

Dimension of array 1
Dimension of array 3
Shape of an array (4, 2, 3)
Shape of array (2, 3)


In [13]:
l1=[12,4,5,7]
l1*3

[12, 4, 5, 7, 12, 4, 5, 7, 12, 4, 5, 7]

In [14]:
for i in l1:
  print(i*3)

36
12
15
21


In [15]:
# convert list to array

new_arr=np.array(l1)
print(type(new_arr))

<class 'numpy.ndarray'>


In [16]:
new_arr*4

array([48, 16, 20, 28])

In [17]:
print(new_arr)
new_arr.sum()

[12  4  5  7]


np.int64(28)

In [18]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [19]:
# arange function
x=np.arange(15,31)
x

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [20]:
# arange function
np.arange(5,18,2)

array([ 5,  7,  9, 11, 13, 15, 17])

In [21]:
x.shape

(16,)

In [22]:
# changing the dimension of array / rearrange the array elements
print("Dimension of array=",x.ndim)
print(x.reshape((2,8)))  # 16 , 2*8  , 4* 4  , 2*4*2
print(x.reshape(4,4))
print(x.reshape(2,4,2))

Dimension of array= 1
[[15 16 17 18 19 20 21 22]
 [23 24 25 26 27 28 29 30]]
[[15 16 17 18]
 [19 20 21 22]
 [23 24 25 26]
 [27 28 29 30]]
[[[15 16]
  [17 18]
  [19 20]
  [21 22]]

 [[23 24]
  [25 26]
  [27 28]
  [29 30]]]


### linspace ()
The linspace() Function: This function creates an array containing a fixed number of numbers
between two specific numbers such that the difference between
any two consecutive numbers in the array is constant.


In [23]:
l = np.linspace(4,7,1)
l

array([4.])

In [24]:
# create an array
#linespace(start, stop, Size)
la=np.linspace(2,5,19)
la

array([2.        , 2.16666667, 2.33333333, 2.5       , 2.66666667,
       2.83333333, 3.        , 3.16666667, 3.33333333, 3.5       ,
       3.66666667, 3.83333333, 4.        , 4.16666667, 4.33333333,
       4.5       , 4.66666667, 4.83333333, 5.        ])

The ndarray() Function<br>
we can create a NumPy array containing some random values using ndarray() function.



In [25]:
# generate random numbers
# we want to create a NumPy array having some random integer values which have 5 rows and 2 columns, then you can use the ndarray() function.

np.ndarray((5,2),dtype=int)


array([[25895968444448860, 23925768161198147],
       [32370111954616435, 30681201962451036],
       [18296268630392937, 27303364806049904],
       [21392493373358196, 30399714103066735],
       [30681206258663516,               112]])

In [26]:
# Generating random numbers in numpy
# using np.random.random(size=n)
np.random.random(50)



array([0.40696736, 0.65192402, 0.6355662 , 0.41751706, 0.08862196,
       0.61110967, 0.93016677, 0.02117244, 0.76430138, 0.85288665,
       0.83854247, 0.81302727, 0.63134953, 0.63827586, 0.79123587,
       0.82856831, 0.11342022, 0.99926922, 0.0665289 , 0.07068525,
       0.68109465, 0.62309311, 0.83167148, 0.35263151, 0.30901805,
       0.30952301, 0.45247597, 0.18728273, 0.84732402, 0.40699266,
       0.53327297, 0.51842337, 0.04444726, 0.57365983, 0.2631394 ,
       0.02347856, 0.41415332, 0.95675751, 0.71954619, 0.76301204,
       0.9179411 , 0.52090987, 0.77420347, 0.91267702, 0.08359709,
       0.62179647, 0.19739609, 0.48553959, 0.08898864, 0.71501864])

In [27]:
# using np.random.randint(low,high,size)

np.random.randint(5,18,4)

array([13,  6, 13,  6], dtype=int32)

In [28]:
# generate random number when two dice are
np.random.randint(1,7,2)

array([1, 1], dtype=int32)

# using np.random.normal
np.random.normal() is a function provided by NumPy for generating random numbers from a normal (Gaussian) distribution. The function allows you to specify the mean
and standard deviation of the distribution, as well as the shape of the output array.



In [29]:
# Syntax: np.random.normal(mean, standard_deviation, size)

In [30]:
np.random.normal(5,2,10)

array([4.6989035 , 4.82330478, 2.48575652, 7.20571123, 6.90576261,
       7.75490068, 3.04339562, 4.87742464, 0.60751257, 3.96603631])

In [31]:
import numpy as np

# Generate random numbers from a normal distribution

mean = 0   # Mean of the distribution
std_dev = 1  # Standard deviation of the distribution
size = (30)  # Shape of the output array (3x3 in this case)

random_numbers = np.random.normal(mean, std_dev, size)
print("Random numbers from a normal distribution:")
print(random_numbers)


Random numbers from a normal distribution:
[-0.78093791  0.54977221 -1.01830196 -0.89367218  0.1832645   0.22244159
 -0.30434494  1.19507142  1.58297038 -0.29967313 -0.27283737  0.46138969
 -1.91157887 -0.7317551   0.77569473 -0.25247722 -0.19309181  1.28733662
  0.44739457  0.37633168 -1.20199056 -1.49655581  2.82790201 -0.48629801
  0.37647741 -1.36435918 -0.91266949 -0.69654499  0.31867851  0.33126757]


The np.random.normal() function is useful for generating random data for simulation, testing,
or any scenario where random numbers from a normal distribution are needed.

In [32]:
# Convert a Python list into a NumPy array using the 'array()' function.

# Define a Python list
py_list = [1, 2, 3, 4, 5]

# Convert the list to a NumPy array
np_array = np.array(py_list)

print("Python list:", py_list)
print("NumPy array:", np_array)
print("Type:", type(np_array))

Python list: [1, 2, 3, 4, 5]
NumPy array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>
